channels:
- id: 1
  name: CH01
- id: 2
  name: CH02
- id: 3
  name: CH03
- id: 4
  name: CH04
- id: 5
  name: CH05
- id: 6
  name: CH06
- id: 7
  name: CH07
- id: 8
  name: CH08
- id: 9
  name: CH09
- id: 10
  name: CH10
- id: 11
  name: CH11
- id: 12
  name: CH12
- id: 13
  name: CH13
- id: 14
  name: CH14
- id: 15
  name: CH15
- id: 16
  name: CH16
- id: 17
  name: CH17
- id: 18
  name: CH18
- id: 19
  name: CH19
- id: 20
  name: CH20
- id: 21
  name: CH21
- id: 22
  name: CH22
- id: 23
  name: CH23
- id: 24
  name: CH24
- id: 25
  name: CH25
- id: 26
  name: CH26
- id: 27
  name: CH27
- id: 28
  name: CH28
- id: 29
  name: CH29
- id: 30
  name: CH30
- id: 31
  name: CH31
- id: 32
  name: CH32
compression: none
sample_rate: 48000
